#!/usr/bin/env python3

import argparse
import csv
import math
from collections import OrderedDict
from pathlib import Path

import matplotlib.pyplot as plt


DISPLAY_LABELS = OrderedDict(
    [
        ("package", "Classes per package"),
        ("class", "Methods per class"),
        ("method", "Tokens per method"),
    ]
)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Render package/class/method size distribution plots from CodeAnalysisRunner CSV output."
    )
    parser.add_argument(
        "input_csv",
        nargs="?",
        default="size_distribution_plot.csv",
        help="CSV file generated by CodeAnalysisRunner boxplotdistributionplot",
    )
    parser.add_argument(
        "-o",
        "--output",
        default="size_distribution_plot.png",
        help="Output figure path",
    )
    parser.add_argument(
        "--title",
        default="Distribution of package, class, and method sizes",
        help="Figure title",
    )
    return parser.parse_args()


def load_series(csv_path):
    series = OrderedDict((key, []) for key in DISPLAY_LABELS)
    with open(csv_path, newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            level = row["level"].strip()
            if level not in series:
                continue
            series[level].append(int(row["size"]))
    return OrderedDict((key, values) for key, values in series.items() if values)


def build_log_bins(values, bin_count=25):
    positive_values = [value for value in values if value > 0]
    if not positive_values:
        return [0, 1]
    if len(set(positive_values)) == 1:
        value = positive_values[0]
        return [max(1, value - 1), value, value + 1]

    minimum = min(positive_values)
    maximum = max(positive_values)
    log_min = math.log10(minimum)
    log_max = math.log10(maximum)
    if log_min == log_max:
        log_max += 1e-9

    return [10 ** (log_min + (log_max - log_min) * index / bin_count) for index in range(bin_count + 1)]


def render(series, output_path, title):
    labels = [DISPLAY_LABELS[key] for key in series]
    values = [series[key] for key in series]
    colors = ["#2F6B7C", "#C06C45", "#6A994E"]

    figure, axes = plt.subplots(1, 3, figsize=(15, 4.8))
    figure.suptitle(title, fontsize=14)

    boxplot = axes[0].boxplot(values, patch_artist=True, labels=labels, showfliers=False)
    for patch, color in zip(boxplot["boxes"], colors):
        patch.set_facecolor(color)
        patch.set_alpha(0.8)
    axes[0].set_title("Boxplot")
    axes[0].set_ylabel("Size")
    axes[0].tick_params(axis="x", rotation=15)

    violin = axes[1].violinplot(values, showmeans=True, showmedians=True)
    for body, color in zip(violin["bodies"], colors):
        body.set_facecolor(color)
        body.set_edgecolor(color)
        body.set_alpha(0.75)
    axes[1].set_title("Violin plot")
    axes[1].set_xticks(range(1, len(labels) + 1))
    axes[1].set_xticklabels(labels, rotation=15)
    axes[1].set_ylabel("Size")

    combined = [value for group in values for value in group]
    bins = build_log_bins(combined)
    for key, color in zip(series, colors):
        axes[2].hist(
            series[key],
            bins=bins,
            alpha=0.5,
            label=DISPLAY_LABELS[key],
            color=color,
        )
    axes[2].set_xscale("log")
    axes[2].set_title("Log-scale histogram")
    axes[2].set_xlabel("Size")
    axes[2].set_ylabel("Frequency")
    axes[2].legend(frameon=False)

    figure.tight_layout()
    figure.savefig(output_path, dpi=200, bbox_inches="tight")


def main():
    args = parse_args()
    input_path = Path(args.input_csv)
    output_path = Path(args.output)
    series = load_series(input_path)
    if not series:
        raise SystemExit(f"No plot data found in {input_path}")
    render(series, output_path, args.title)


if __name__ == "__main__":
    main()
